package cppgen

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// ---------------------------------------------------------------------------
// Formatter header (*.fmt.h)
// ---------------------------------------------------------------------------
//
// Emits free `to_ostream(logfmt::context&, const T&)` overloads for every DTO
// message and enum, in the DTO namespace so they are found via ADL by the
// logfmt machinery (including from inside its container printers). This lets
// `logfmt::to_string(dto)` render an arbitrarily nested DTO.

func (g *fileGen) genFmtHeader(gen *protogen.Plugin, base string) {
	out := gen.NewGeneratedFile(base+".fmt.h", "")
	out.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	out.P("// source: ", g.f.Desc.Path())
	out.P("#pragma once")
	out.P()
	out.P("#include \"", base, ".dto.h\"")
	out.P("#include \"", g.opts.LogFormatInclude, "\"")

	// Pull in the formatter overloads for imported DTO types this file uses.
	imps := g.f.Desc.Imports()
	for i := 0; i < imps.Len(); i++ {
		p := imps.Get(i).Path()
		if strings.HasPrefix(p, "google/protobuf/") {
			continue // well-known types are not supported
		}
		out.P("#include \"", strings.TrimSuffix(p, ".proto"), ".fmt.h\"")
	}
	if g.usesWellKnown() {
		out.P("#include \"", wellKnownFmtInclude, "\"")
	}
	out.P()

	g.openNamespace(out)
	for _, e := range g.fileEnums() {
		out.P("void to_ostream(::logfmt::context& ctx, ", localName(e.Desc), " v);")
	}
	for _, m := range g.keptMessages() {
		out.P("void to_ostream(::logfmt::context& ctx, const ", localName(m.Desc), "& v);")
	}
	g.closeNamespace(out)
}

// ---------------------------------------------------------------------------
// Formatter source (*.fmt.cc)
// ---------------------------------------------------------------------------

func (g *fileGen) genFmtSource(gen *protogen.Plugin, base string) {
	out := gen.NewGeneratedFile(base+".fmt.cc", "")
	out.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	out.P("// source: ", g.f.Desc.Path())
	out.P("#include \"", base, ".fmt.h\"")
	out.P()
	g.openNamespace(out)
	for _, e := range g.fileEnums() {
		g.emitEnumFormatter(out, e)
	}
	for _, m := range g.keptMessages() {
		g.emitMessageFormatter(out, m)
	}
	g.closeNamespace(out)
}

// emitEnumFormatter prints the enum value's name, falling back to its numeric
// value for anything unknown (e.g. a value added on the wire since generation).
func (g *fileGen) emitEnumFormatter(out *protogen.GeneratedFile, e *protogen.Enum) {
	name := localName(e.Desc)
	out.P("void to_ostream(::logfmt::context& ctx, ", name, " v) {")
	out.P("  switch (v) {")
	seen := map[protoreflect.EnumNumber]bool{}
	for _, v := range e.Values {
		// Skip aliases (allow_alias): duplicate case labels would not compile.
		if seen[v.Desc.Number()] {
			continue
		}
		seen[v.Desc.Number()] = true
		vn := string(v.Desc.Name())
		out.P("    case ", name, "::", vn, ": ctx << \"", vn, "\"; return;")
	}
	out.P("    default: ctx << static_cast<::std::int32_t>(v); return;")
	out.P("  }")
	out.P("}")
	out.P()
}

// emitMessageFormatter renders a message as `Name { field: value, ... }`,
// driving layout through the context so it works in both multi-line and
// one-line mode. Field values dispatch back through to_ostream (unqualified,
// so ADL selects the logfmt overload for std types or the DTO overload for
// nested messages/enums).
func (g *fileGen) emitMessageFormatter(out *protogen.GeneratedFile, m *protogen.Message) {
	name := localName(m.Desc)
	out.P("void to_ostream(::logfmt::context& ctx, const ", name, "& v) {")
	out.P("  ctx << \"", name, " {\";")
	out.P("  ctx.newline();")
	out.P("  ctx.inc_indent();")

	// Collect members first so we can place a separator between (but not after)
	// them; the trailing separator would otherwise dangle before the '}'.
	var emit []func()
	g.forEachMember(m,
		func(fld *protogen.Field) { emit = append(emit, func() { g.fieldFormat(out, fld) }) },
		func(o *protogen.Oneof) { emit = append(emit, func() { g.oneofFormat(out, o) }) },
	)
	for i, e := range emit {
		out.P("  ctx.indent();")
		e()
		if i < len(emit)-1 {
			out.P("  ctx << \",\";")
		}
		out.P("  ctx.newline();")
	}

	out.P("  ctx.dec_indent();")
	out.P("  ctx.indent();")
	out.P("  ctx << \"}\";")
	out.P("}")
	out.P()
}

func (g *fileGen) fieldFormat(out *protogen.GeneratedFile, fld *protogen.Field) {
	name := string(fld.Desc.Name())
	out.P("  ctx << \"", name, ": \";")
	out.P("  to_ostream(ctx, v.", sanitize(name), ");")
}

// oneofFormat prints the active alternative as `oneof.field: value`, switching
// on the variant index so alternatives that share a C++ type (e.g. two string
// fields) are still labelled correctly.
func (g *fileGen) oneofFormat(out *protogen.GeneratedFile, o *protogen.Oneof) {
	oname := string(o.Desc.Name())
	mem := "v." + sanitize(oname)
	out.P("  switch (", mem, ".index()) {")
	for idx, fld := range o.Fields {
		n := idx + 1 // variant index 0 is std::monostate
		fname := string(fld.Desc.Name())
		out.P("    case ", n, ":")
		out.P("      ctx << \"", oname, ".", fname, ": \";")
		out.P("      to_ostream(ctx, ::std::get<", n, ">(", mem, "));")
		out.P("      break;")
	}
	out.P("    default:")
	out.P("      ctx << \"", oname, ": (unset)\";")
	out.P("      break;")
	out.P("  }")
}
