package cppgen

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Run generates DTO and conversion files for every file protoc asked us to
// generate.
func Run(gen *protogen.Plugin, opts Options) error {
	if opts.NamespaceSuffix == "" {
		opts.NamespaceSuffix = "dto"
	}
	if opts.BytesType == "" {
		opts.BytesType = "::std::string"
	}

	// Recursion is unsupported; fail fast before emitting anything.
	if err := checkAcyclic(gen.Files); err != nil {
		return err
	}

	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if f.Desc.Syntax() != protoreflect.Proto3 {
			return fmt.Errorf("%s: only proto3 is supported", f.Desc.Path())
		}
		g := &fileGen{opts: opts, f: f}
		g.generate(gen)
	}
	return nil
}

type fileGen struct {
	opts Options
	f    *protogen.File
}

func (g *fileGen) generate(gen *protogen.Plugin) {
	base := strings.TrimSuffix(g.f.Desc.Path(), ".proto")
	g.genDtoHeader(gen, base)
	g.genConvHeader(gen, base)
	g.genConvSource(gen, base)
}

// nsParts returns the C++ namespace components for the DTO namespace, e.g.
// package "a.b" with suffix "dto" -> ["a", "b", "dto"].
func (g *fileGen) nsParts() []string {
	var parts []string
	if pkg := string(g.f.Desc.Package()); pkg != "" {
		parts = append(parts, strings.Split(pkg, ".")...)
	}
	return append(parts, g.opts.NamespaceSuffix)
}

func (g *fileGen) openNamespace(out *protogen.GeneratedFile) {
	for _, ns := range g.nsParts() {
		out.P("namespace ", ns, " {")
	}
	out.P()
}

func (g *fileGen) closeNamespace(out *protogen.GeneratedFile) {
	out.P()
	parts := g.nsParts()
	for i := len(parts) - 1; i >= 0; i-- {
		out.P("}  // namespace ", parts[i])
	}
}

// localName returns the in-namespace (flattened) DTO name for a message/enum.
func localName(d protoreflect.Descriptor) string {
	return flatName(d.FullName(), d.ParentFile().Package())
}

// fileMessages returns all real messages in this file, flattened.
func (g *fileGen) fileMessages() []*protogen.Message {
	return flattenMessages(g.f.Messages)
}

func flattenMessages(list []*protogen.Message) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range list {
		if m.Desc.IsMapEntry() {
			continue
		}
		out = append(out, m)
		out = append(out, flattenMessages(m.Messages)...)
	}
	return out
}

// fileEnums returns all enums in this file (top-level and nested).
func (g *fileGen) fileEnums() []*protogen.Enum {
	enums := append([]*protogen.Enum{}, g.f.Enums...)
	for _, m := range g.fileMessages() {
		enums = append(enums, m.Enums...)
	}
	return enums
}

// ---------------------------------------------------------------------------
// DTO header
// ---------------------------------------------------------------------------

func (g *fileGen) genDtoHeader(gen *protogen.Plugin, base string) {
	out := gen.NewGeneratedFile(base+".dto.h", "")
	out.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	out.P("// source: ", g.f.Desc.Path())
	out.P("#pragma once")
	out.P()
	out.P("#include <cstdint>")
	out.P("#include <map>")
	out.P("#include <optional>")
	out.P("#include <string>")
	out.P("#include <variant>")
	out.P("#include <vector>")

	imps := g.f.Desc.Imports()
	for i := 0; i < imps.Len(); i++ {
		p := imps.Get(i).Path()
		if strings.HasPrefix(p, "google/protobuf/") {
			continue // well-known types are not supported
		}
		out.P("#include \"", strings.TrimSuffix(p, ".proto"), ".dto.h\"")
	}
	out.P()

	g.openNamespace(out)

	for _, e := range g.fileEnums() {
		g.emitEnum(out, e)
	}
	for _, m := range g.topoSort(g.fileMessages()) {
		g.emitStruct(out, m)
	}

	g.closeNamespace(out)
}

func (g *fileGen) emitEnum(out *protogen.GeneratedFile, e *protogen.Enum) {
	out.P("enum class ", localName(e.Desc), " : ::std::int32_t {")
	for _, v := range e.Values {
		out.P("  ", string(v.Desc.Name()), " = ", int(v.Desc.Number()), ",")
	}
	out.P("};")
	out.P()
}

func (g *fileGen) emitStruct(out *protogen.GeneratedFile, m *protogen.Message) {
	out.P("struct ", localName(m.Desc), " {")
	// Every member is value-initialized with `{}` so a default-constructed DTO
	// matches proto3 zero defaults and never holds an indeterminate value.
	g.forEachMember(m,
		func(fld *protogen.Field) {
			out.P("  ", g.opts.memberType(fld.Desc), " ", sanitize(string(fld.Desc.Name())), "{};")
		},
		func(o *protogen.Oneof) {
			out.P("  ", g.variantType(o), " ", sanitize(string(o.Desc.Name())), "{};")
		},
	)
	out.P("};")
	out.P()
}

func (g *fileGen) variantType(o *protogen.Oneof) string {
	parts := []string{"::std::monostate"}
	for _, fld := range o.Fields {
		parts = append(parts, g.opts.cppElemType(fld.Desc))
	}
	return "::std::variant<" + strings.Join(parts, ", ") + ">"
}

// forEachMember walks a message's fields, invoking onField for plain fields
// (including proto3 `optional`, which protoc models as a synthetic oneof) and
// onOneof once per real oneof, in field declaration order.
func (g *fileGen) forEachMember(m *protogen.Message, onField func(*protogen.Field), onOneof func(*protogen.Oneof)) {
	seen := map[string]bool{}
	for _, fld := range m.Fields {
		if fld.Oneof != nil && !fld.Oneof.Desc.IsSynthetic() {
			name := string(fld.Oneof.Desc.Name())
			if seen[name] {
				continue
			}
			seen[name] = true
			onOneof(fld.Oneof)
			continue
		}
		onField(fld)
	}
}

// topoSort orders messages so that a struct is defined after every same-file
// message it embeds by value. The graph is guaranteed acyclic by checkAcyclic.
func (g *fileGen) topoSort(msgs []*protogen.Message) []*protogen.Message {
	byName := map[protoreflect.FullName]*protogen.Message{}
	for _, m := range msgs {
		byName[m.Desc.FullName()] = m
	}
	const (
		gray  = 1
		black = 2
	)
	state := map[protoreflect.FullName]int{}
	var order []*protogen.Message

	var visit func(m *protogen.Message)
	visit = func(m *protogen.Message) {
		if state[m.Desc.FullName()] == black {
			return
		}
		state[m.Desc.FullName()] = gray
		for _, dep := range g.sameFileMsgDeps(m) {
			if dm, ok := byName[dep]; ok && state[dep] != gray {
				visit(dm)
			}
		}
		state[m.Desc.FullName()] = black
		order = append(order, m)
	}
	for _, m := range msgs {
		visit(m)
	}
	return order
}

// sameFileMsgDeps returns the full names of messages defined in this file that
// the given message references through its fields.
func (g *fileGen) sameFileMsgDeps(m *protogen.Message) []protoreflect.FullName {
	path := g.f.Desc.Path()
	var deps []protoreflect.FullName
	add := func(md protoreflect.MessageDescriptor) {
		if md != nil && md.ParentFile().Path() == path {
			deps = append(deps, md.FullName())
		}
	}
	fields := m.Desc.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		switch {
		case fd.IsMap():
			if mv := fd.MapValue(); isMessageField(mv) {
				add(mv.Message())
			}
		case isMessageField(fd):
			add(fd.Message())
		}
	}
	return deps
}

// ---------------------------------------------------------------------------
// Conversion header
// ---------------------------------------------------------------------------

func (g *fileGen) genConvHeader(gen *protogen.Plugin, base string) {
	out := gen.NewGeneratedFile(base+".conv.h", "")
	out.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	out.P("// source: ", g.f.Desc.Path())
	out.P("#pragma once")
	out.P()
	out.P("#include \"", base, ".dto.h\"")
	out.P("#include \"", base, ".pb.h\"")
	out.P()
	g.openNamespace(out)
	for _, m := range g.fileMessages() {
		dto := localName(m.Desc)
		proto := protoFQN(m.Desc)
		out.P("void from_proto(const ", proto, "& src, ", dto, "& dst);")
		out.P("void to_proto(const ", dto, "& src, ", proto, "* dst);")
	}
	g.closeNamespace(out)
}

// ---------------------------------------------------------------------------
// Conversion source
// ---------------------------------------------------------------------------

func (g *fileGen) genConvSource(gen *protogen.Plugin, base string) {
	out := gen.NewGeneratedFile(base+".conv.cc", "")
	out.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	out.P("// source: ", g.f.Desc.Path())
	out.P("#include \"", base, ".conv.h\"")
	out.P()
	out.P("#include <utility>")
	out.P()
	g.openNamespace(out)
	for _, m := range g.fileMessages() {
		g.emitFromProto(out, m)
		g.emitToProto(out, m)
	}
	g.closeNamespace(out)
}

func (g *fileGen) emitFromProto(out *protogen.GeneratedFile, m *protogen.Message) {
	out.P("void from_proto(const ", protoFQN(m.Desc), "& src, ", localName(m.Desc), "& dst) {")
	g.forEachMember(m,
		func(fld *protogen.Field) { g.fieldFromProto(out, fld) },
		func(o *protogen.Oneof) { g.oneofFromProto(out, m, o) },
	)
	out.P("}")
	out.P()
}

func (g *fileGen) emitToProto(out *protogen.GeneratedFile, m *protogen.Message) {
	out.P("void to_proto(const ", localName(m.Desc), "& src, ", protoFQN(m.Desc), "* dst) {")
	out.P("  dst->Clear();")
	g.forEachMember(m,
		func(fld *protogen.Field) { g.fieldToProto(out, fld) },
		func(o *protogen.Oneof) { g.oneofToProto(out, o) },
	)
	out.P("}")
	out.P()
}

// fromScalar wraps a protobuf-side scalar/enum expression so it yields the DTO type.
func (g *fileGen) fromScalar(fd protoreflect.FieldDescriptor, expr string) string {
	if fd.Kind() == protoreflect.EnumKind {
		return "static_cast<" + g.opts.dtoEnumFQN(fd.Enum()) + ">(static_cast<int>(" + expr + "))"
	}
	return expr
}

// toScalar wraps a DTO-side scalar/enum expression so it yields the protobuf type.
func (g *fileGen) toScalar(fd protoreflect.FieldDescriptor, expr string) string {
	if fd.Kind() == protoreflect.EnumKind {
		return "static_cast<" + protoEnumFQN(fd.Enum()) + ">(static_cast<int>(" + expr + "))"
	}
	return expr
}

func (g *fileGen) fieldFromProto(out *protogen.GeneratedFile, fld *protogen.Field) {
	fd := fld.Desc
	acc := strings.ToLower(string(fd.Name()))
	mem := "dst." + sanitize(string(fd.Name()))

	switch {
	case fd.IsMap():
		val := fd.MapValue()
		out.P("  ", mem, ".clear();")
		out.P("  for (const auto& kv : src.", acc, "()) {")
		if isMessageField(val) {
			out.P("    ", g.opts.cppElemType(val), " v;")
			out.P("    from_proto(kv.second, v);")
			out.P("    ", mem, "[kv.first] = ::std::move(v);")
		} else {
			out.P("    ", mem, "[kv.first] = ", g.fromScalar(val, "kv.second"), ";")
		}
		out.P("  }")

	case fd.IsList():
		out.P("  ", mem, ".clear();")
		out.P("  ", mem, ".reserve(src.", acc, "_size());")
		out.P("  for (int i = 0; i < src.", acc, "_size(); ++i) {")
		if isMessageField(fd) {
			out.P("    ", g.opts.cppElemType(fd), " v;")
			out.P("    from_proto(src.", acc, "(i), v);")
			out.P("    ", mem, ".push_back(::std::move(v));")
		} else {
			out.P("    ", mem, ".push_back(", g.fromScalar(fd, "src."+acc+"(i)"), ");")
		}
		out.P("  }")

	case isMessageField(fd):
		out.P("  if (src.has_", acc, "()) {")
		out.P("    ", g.opts.cppElemType(fd), " v;")
		out.P("    from_proto(src.", acc, "(), v);")
		out.P("    ", mem, " = ::std::move(v);")
		out.P("  } else {")
		out.P("    ", mem, ".reset();")
		out.P("  }")

	case fd.HasPresence():
		out.P("  if (src.has_", acc, "()) {")
		out.P("    ", mem, " = ", g.fromScalar(fd, "src."+acc+"()"), ";")
		out.P("  } else {")
		out.P("    ", mem, ".reset();")
		out.P("  }")

	default:
		out.P("  ", mem, " = ", g.fromScalar(fd, "src."+acc+"()"), ";")
	}
}

func (g *fileGen) fieldToProto(out *protogen.GeneratedFile, fld *protogen.Field) {
	fd := fld.Desc
	acc := strings.ToLower(string(fd.Name()))
	mem := "src." + sanitize(string(fd.Name()))

	switch {
	case fd.IsMap():
		val := fd.MapValue()
		out.P("  for (const auto& kv : ", mem, ") {")
		if isMessageField(val) {
			out.P("    to_proto(kv.second, &(*dst->mutable_", acc, "())[kv.first]);")
		} else {
			out.P("    (*dst->mutable_", acc, "())[kv.first] = ", g.toScalar(val, "kv.second"), ";")
		}
		out.P("  }")

	case fd.IsList():
		out.P("  for (const auto& v : ", mem, ") {")
		if isMessageField(fd) {
			out.P("    to_proto(v, dst->add_", acc, "());")
		} else {
			out.P("    dst->add_", acc, "(", g.toScalar(fd, "v"), ");")
		}
		out.P("  }")

	case isMessageField(fd):
		out.P("  if (", mem, ") {")
		out.P("    to_proto(*", mem, ", dst->mutable_", acc, "());")
		out.P("  }")

	case fd.HasPresence():
		out.P("  if (", mem, ") {")
		out.P("    dst->set_", acc, "(", g.toScalar(fd, "*"+mem), ");")
		out.P("  }")

	default:
		out.P("  dst->set_", acc, "(", g.toScalar(fd, mem), ");")
	}
}

func (g *fileGen) oneofFromProto(out *protogen.GeneratedFile, m *protogen.Message, o *protogen.Oneof) {
	proto := protoFQN(m.Desc)
	oname := string(o.Desc.Name())
	mem := "dst." + sanitize(oname)
	out.P("  switch (src.", strings.ToLower(oname), "_case()) {")
	for idx, fld := range o.Fields {
		n := idx + 1 // variant index 0 is std::monostate
		acc := strings.ToLower(string(fld.Desc.Name()))
		label := proto + "::k" + upperCamel(string(fld.Desc.Name()))
		if isMessageField(fld.Desc) {
			out.P("    case ", label, ": {")
			out.P("      ", g.opts.cppElemType(fld.Desc), " v;")
			out.P("      from_proto(src.", acc, "(), v);")
			out.P("      ", mem, ".emplace<", n, ">(::std::move(v));")
			out.P("      break;")
			out.P("    }")
		} else {
			out.P("    case ", label, ":")
			out.P("      ", mem, ".emplace<", n, ">(", g.fromScalar(fld.Desc, "src."+acc+"()"), ");")
			out.P("      break;")
		}
	}
	out.P("    default:")
	out.P("      ", mem, ".emplace<0>();")
	out.P("      break;")
	out.P("  }")
}

func (g *fileGen) oneofToProto(out *protogen.GeneratedFile, o *protogen.Oneof) {
	mem := "src." + sanitize(string(o.Desc.Name()))
	out.P("  switch (", mem, ".index()) {")
	for idx, fld := range o.Fields {
		n := strconv.Itoa(idx + 1)
		acc := strings.ToLower(string(fld.Desc.Name()))
		get := "::std::get<" + n + ">(" + mem + ")"
		out.P("    case ", idx+1, ":")
		if isMessageField(fld.Desc) {
			out.P("      to_proto(", get, ", dst->mutable_", acc, "());")
		} else {
			out.P("      dst->set_", acc, "(", g.toScalar(fld.Desc, get), ");")
		}
		out.P("      break;")
	}
	// index 0 (std::monostate) leaves the oneof cleared by dst->Clear().
	out.P("    default:")
	out.P("      break;")
	out.P("  }")
}
