package cppgen

import (
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Well-known types (the google.protobuf.* messages shipped with protobuf) have
// no proto3 source we generate DTOs from, so we map the supported ones to
// hand-written passthrough DTO types defined in shared support headers. These
// live in a fixed `cppdto::wellknown` namespace, independent of the user's
// --dto_namespace_suffix, and are emitted once per protoc invocation into the
// paths below (resolved relative to the output root, like every other include).
const (
	wellKnownDTOInclude  = "cppdto/well_known.dto.h"
	wellKnownConvInclude = "cppdto/well_known.conv.h"
	wellKnownFmtInclude  = "cppdto/well_known.fmt.h"
)

// wellKnownDTOType returns the C++ DTO type for a supported well-known message
// type, or ("", false) if the message is not a (supported) well-known type.
//
// google.protobuf.Any is a type-erased container: a serialized payload plus a
// type URL naming its concrete message. The set of payload types is open, so it
// cannot be expressed as a std::variant; we map it to a passthrough struct that
// carries the two fields verbatim.
func wellKnownDTOType(md protoreflect.MessageDescriptor) (string, bool) {
	switch md.FullName() {
	case "google.protobuf.Any":
		return "::cppdto::wellknown::Any", true
	}
	return "", false
}

// messageUsesWellKnown reports whether any field of md references a supported
// well-known type (as a singular, repeated, or map-value message).
func messageUsesWellKnown(md protoreflect.MessageDescriptor) bool {
	fields := md.Fields()
	for i := 0; i < fields.Len(); i++ {
		fd := fields.Get(i)
		var target protoreflect.MessageDescriptor
		switch {
		case fd.IsMap():
			if mv := fd.MapValue(); isMessageField(mv) {
				target = mv.Message()
			}
		case isMessageField(fd):
			target = fd.Message()
		}
		if target != nil {
			if _, ok := wellKnownDTOType(target); ok {
				return true
			}
		}
	}
	return false
}

// usesWellKnown reports whether any kept message in this file references a
// supported well-known type, i.e. whether the file's generated headers need to
// include the well-known support headers.
func (g *fileGen) usesWellKnown() bool {
	for _, m := range g.keptMessages() {
		if messageUsesWellKnown(m.Desc) {
			return true
		}
	}
	return false
}

// anyUsesWellKnown reports whether any generated file uses a supported
// well-known type, so Run knows whether to emit the shared support headers.
func anyUsesWellKnown(files []*protogen.File, dropped map[protoreflect.FullName]bool) bool {
	for _, f := range files {
		if !f.Generate {
			continue
		}
		for _, md := range allMessageDescs(f.Desc.Messages()) {
			if dropped[md.FullName()] {
				continue
			}
			if messageUsesWellKnown(md) {
				return true
			}
		}
	}
	return false
}

// emitWellKnownSupport writes the shared well-known DTO, conversion, and (when
// formatters are enabled) formatter headers. Called once per invocation.
func emitWellKnownSupport(gen *protogen.Plugin, opts Options) {
	dto := gen.NewGeneratedFile(wellKnownDTOInclude, "")
	dto.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	dto.P("// Passthrough DTOs for supported google.protobuf well-known types.")
	dto.P("#pragma once")
	dto.P()
	dto.P("#include <string>")
	dto.P()
	dto.P("namespace cppdto {")
	dto.P("namespace wellknown {")
	dto.P()
	dto.P("// Passthrough DTO for google.protobuf.Any: the serialized payload plus")
	dto.P("// the type URL that identifies it. The payload is not unpacked; consumers")
	dto.P("// interpret `value` using `type_url`.")
	dto.P("struct Any {")
	dto.P("  ::std::string type_url{};")
	dto.P("  ::std::string value{};")
	dto.P("};")
	dto.P()
	dto.P("}  // namespace wellknown")
	dto.P("}  // namespace cppdto")

	conv := gen.NewGeneratedFile(wellKnownConvInclude, "")
	conv.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	conv.P("#pragma once")
	conv.P()
	conv.P("#include \"", wellKnownDTOInclude, "\"")
	conv.P("#include <google/protobuf/any.pb.h>")
	conv.P()
	conv.P("namespace cppdto {")
	conv.P("namespace wellknown {")
	conv.P()
	conv.P("inline void from_proto(const ::google::protobuf::Any& src, Any& dst) {")
	conv.P("  dst.type_url = src.type_url();")
	conv.P("  dst.value = src.value();")
	conv.P("}")
	conv.P()
	conv.P("inline void to_proto(const Any& src, ::google::protobuf::Any* dst) {")
	conv.P("  dst->set_type_url(src.type_url);")
	conv.P("  dst->set_value(src.value);")
	conv.P("}")
	conv.P()
	conv.P("}  // namespace wellknown")
	conv.P("}  // namespace cppdto")

	if !opts.GenFormatters {
		return
	}
	fmtH := gen.NewGeneratedFile(wellKnownFmtInclude, "")
	fmtH.P("// Code generated by protoc-gen-cppdto. DO NOT EDIT.")
	fmtH.P("#pragma once")
	fmtH.P()
	fmtH.P("#include \"", wellKnownDTOInclude, "\"")
	fmtH.P("#include \"", opts.LogFormatInclude, "\"")
	fmtH.P()
	fmtH.P("namespace cppdto {")
	fmtH.P("namespace wellknown {")
	fmtH.P()
	fmtH.P("inline void to_ostream(::logfmt::context& ctx, const Any& v) {")
	fmtH.P("  ctx << \"Any { type_url: \" << v.type_url")
	fmtH.P("      << \", value: \" << v.value.size() << \" bytes }\";")
	fmtH.P("}")
	fmtH.P()
	fmtH.P("}  // namespace wellknown")
	fmtH.P("}  // namespace cppdto")
}
